- alias: Evening feed
  id: '1566893522713'
  trigger:
  - at: '17:00:00'
    platform: time
  action:
  - service: script.feed_cats
- alias: Morning Feed
  id: '1566993898921'
  trigger:
  - at: 07:00:00
    platform: time
  action:
  - service: script.feed_cats