- id: '1627420103277'
  alias: Lounge Motion Lighting
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lounge_motion
    id: lounge-motion-on
    to: 'on'
  - platform: state
    entity_id: binary_sensor.lounge_motion
    id: lounge-motion-off
    to: 'off'
    for: 00:02:00
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.lounge_state
      state: Idle
    - condition: state
      entity_id: input_select.lounge_state
      state: Motion
  - condition: and
    conditions:
    - condition: sun
      before: sunrise
      after: sunset
      after_offset: -00:45:00
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.in_bed
      state: 'off'
  action:
  - condition: and
    conditions:
    - condition: trigger
      id: lounge-motion-on
    - condition: sun
      before: sunset
      after: sunset
      before_offset: 03:00:00
      after_offset: -00:45:00
  - service: input_select.select_option
    target:
      entity_id: input_select.lounge_state
    data:
      option: Motion
  - service: light.turn_on
    target:
      entity_id: light.lounge
  - condition: and
    conditions:
    - condition: trigger
      id: lounge-motion-on
    - condition: sun
      before: sunrise
      after: sunset
      after_offset: 03:00:00
  - service: yeelight.set_color_temp_scene
    data:
      kelvin: 3700
      brightness: 50
  - service: input_select.select_option
    target:
      entity_id: input_select.lounge_state
    data:
      option: Motion
  - condition: trigger
    id: lounge-motion-off
  - service: input_select.select_option
    target:
      entity_id: input_select.lounge_state
    data:
      option: Idle
  - service: light.turn_off
    target:
      area_id: f7a90e0bdcf941a6ba0ac65e1dc244ee
  mode: restart
