- alias: Update notifications
  id: notify_homeassistant_update
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - service: notify.pushbullet
    data:
      title: New Home Assistant Release
      message: Home Assistant  {{ states.updater.updater.state }}  is now available.
      target:
      - email/mcinnes01@gmail.com
      - device/AndyPhone
- alias: Doorbell Notifications
  id: doorbell_trigger
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    to: 'on'
  action:
  - service: notify.pushbullet
    data:
      title: Doorbell
      message: Ding dong! Someone is at the door!
      data:
        file_url: http://tiptag.com.ar/wp-content/uploads/2018/06/timbre1.jpg
      target:
      - email/mcinnes01@gmail.com
      - device/AndyPhone
  - service: notify.alexa_media
    data:
      title: Doorbell
      message: Ding dong! Someone is at the door!
      target:
      - media_player.everywhere
      data:
        type: announce
- id: alarm_trigger
  alias: Trigger alarm while armed away
  trigger:
  - device_id: f918e214648f4e25848333fcea985dfe
    domain: binary_sensor
    entity_id: binary_sensor.snug_motion
    platform: device
    type: motion
  - device_id: f918e214648f4e25848333fcea985dfe
    domain: binary_sensor
    entity_id: binary_sensor.dining_room_motion
    platform: device
    type: motion
  - device_id: f918e214648f4e25848333fcea985dfe
    domain: binary_sensor
    entity_id: binary_sensor.utility_room_motion
    platform: device
    type: motion
  - device_id: f918e214648f4e25848333fcea985dfe
    domain: binary_sensor
    entity_id: binary_sensor.cellar_door
    platform: device
    type: opened
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  action:
  - data: {}
    entity_id: alarm_control_panel.alarm
    service: alarm_control_panel.alarm_trigger
- alias: Send notification when alarm triggered
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: triggered
  action:
  - data:
      title: Alarm Triggered
      message: ALARM! The alarm has been triggered
      data:
        file_url: https://media.istockphoto.com/vectors/vector-fire-alarm-vector-id610426096?k=6&m=610426096&s=612x612&w=0&h=IIjBibeAUNdoq7XS4-esMGyxxw_xFkb07zbwKcwNB-I=
      target:
      - email/mcinnes01@gmail.com
      - device/AndyPhone
    service: notify.pushbullet
  - data:
      title: Alarm Triggered
      message: The alarm has been triggered. The alarm has been triggered. The alarm
        has been triggered. The alarm has been triggered. The alarm has been triggered.
      target:
      - media_player.everywhere
      data:
        type: announce
    service: notify.alexa_media
  id: 33a13ad590164e5a9542f8223820a928
- alias: Turn On Ex Machina lights when alarm triggered
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: triggered
  action:
  - data: {}
    entity_id: light.inside
    service: light.turn_off
  - data:
      brightness_pct: 100
      effect: Alarm
    entity_id: light.yeelights
    service: light.turn_on
  id: 71bcd308a0bc484793b7d78e8ec8e69d
- alias: Send notification when alarm is Disarmed
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: disarmed
  action:
  - data:
      type: announce
    service: notify.alexa_media
    data_template:
      title: Alarm disarmed
      message: ALARM! The alarm is Disarmed at {{ states('sensor.date_time') }}
      target:
      - media_player.everywhere
  id: 63385e6035f643aab8b67f619af4951b
- alias: Turn Off Ex Machina lights when alarm disarmed
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: disarmed
  action:
  - data:
      effect: Stop
    entity_id: light.yeelights
    service: light.turn_on
  - data: {}
    entity_id: light.yeelights
    service: light.turn_off
  id: 71bcd308a0bc484793b7d78e8ec8e69f
- alias: Send notification when alarm is arming
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    from: disarmed
    to: pending
  action:
  - service: notify.alexa_media
    data_template:
      title: Alarm arming
      message: The alarm is arming you have 60 seconds to leave
      target:
      - media_player.everywhere
      data:
        type: announce
  id: a71c90774150444f9237ba14769e935a
- alias: Send notification when alarm is pending
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    from: armed
    to: pending
  action:
  - service: notify.alexa_media
    data_template:
      title: Alarm pending
      message: You have 30 seconds to disable the alarm
      target:
      - media_player.everywhere
      data:
        type: announce
  id: df6ae52914e648ec8d170fc4e508c29e
- alias: Send notification when alarm is Armed in Away mode
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: armed_away
  action:
  - service: notify.alexa_media
    data_template:
      title: Alarm armed in away mode
      message: The alarm is armed in Away mode
      target:
      - media_player.everywhere
      data:
        type: announce
  id: e430701364844f3da246e6f2db218214
- alias: Send notification when alarm is Armed in Home mode
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: armed_home
  action:
  - service: notify.alexa_media
    data_template:
      title: Alarm armed in home mode
      message: The alarm is armed in Home mode
      target:
      - media_player.everywhere
      data:
        type: announce
  id: b762a0f5608845a2800b4b408924d844
- alias: Patio Motion
  id: '1560465284215'
  trigger:
  - platform: webhook
    webhook_id: ''
  condition: []
  action: []
- alias: Evening feed
  id: '1566893522713'
  trigger:
  - at: '17:00:00'
    platform: time
  condition: []
  action:
  - service: script.feed_cats
- alias: Morning Feed
  id: '1566993898921'
  trigger:
  - at: 07:00:00
    platform: time
  condition: []
  action:
  - service: script.feed_cats
- id: '1579518320766'
  alias: Turn On Porch Light when Sun is set
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: light.porch
    service: light.turn_on
- id: '1579518409890'
  alias: Turn Off Porch Light at 11pm
  description: ''
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - entity_id: light.porch
    service: light.turn_off
- id: '1587464597280'
  alias: Sump Alarm Triggered
  description: The sump is at risk of overflowing, the pump may be offline or broken
  trigger:
  - device_id: 67c16ded941843d59f95ea1394628b0a
    domain: binary_sensor
    entity_id: binary_sensor.sump_alarm_trigger
    platform: device
    type: turned_on
  condition: []
  action:
  - data:
      title: Sump Alarm Triggered
      message: The sump alarm has been triggered, check the sump pump has power, this
        could cause a flood if not attended.
      data:
        file_url: https://media.istockphoto.com/vectors/vector-fire-alarm-vector-id610426096?k=6&m=610426096&s=612x612&w=0&h=IIjBibeAUNdoq7XS4-esMGyxxw_xFkb07zbwKcwNB-I=
      target:
      - email/mcinnes01@gmail.com
      - device/AndyPhone
    service: notify.pushbullet
  - data:
      title: Sump Alarm Triggered
      message: The sump alarm has been triggered, check the sump pump has power, this
        could cause a flood if not attended.
      target:
      - media_player.everywhere
      data:
        type: announce
    service: notify.alexa_media
- alias: Turn On Lights
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.basement_stairs_motion
    - binary_sensor.basement_hall_motion
    - binary_sensor.snug_motion
    - binary_sensor.dining_room_motion
    - binary_sensor.utility_room_motion
    - binary_sensor.toilet_motion
    - binary_sensor.hall_motion
    - binary_sensor.lounge_motion
    - binary_sensor.drawing_room_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.landing_motion
    - binary_sensor.studio_motion
    - binary_sensor.bathroom_motion
    - binary_sensor.bedroom_motion
    - binary_sensor.guest_room_motion
    - binary_sensor.dressing_room_motion
    to: 'on'
  mode: parallel
  action:
  - choose:
    - conditions:
        condition: template
        value_template: '{% set room = trigger.to_state.object_id[:-7] %} {{ room
          == ''basement_stairs'' }}

          '
      sequence:
      - service: light.turn_on
        data_template:
          entity_id: 'light.basement_hall

            '
    - conditions:
      - condition: template
        value_template: '{{ is_state(''input_select.ambience'', ''Ambient'') }}'
      sequence:
      - service: light.turn_on
        data_template:
          entity_id: '{% set room = trigger.to_state.object_id[:-7] %} {% set rooms
            = [''lounge'', ''hallway'', ''kitchen'', ''bedroom'', ''snug'', ''drawing_room'']
            %} light.{{ room }}{% if room in rooms %}_lamp{% endif %}

            '
    - conditions:
        condition: template
        value_template: '{{ states(''input_select.ambience'') in [''Bright'', ''Evening'']
          }}'
      sequence:
      - service: light.turn_on
        data_template:
          entity_id: 'light.{{ trigger.to_state.object_id[:-7] }}

            '
    - conditions:
        condition: template
        value_template: '{% set room = trigger.to_state.object_id[:-7] %} {% set rooms
          = [''basement_hall'', ''snug'', ''dining_room'', ''utility_room'', ''toilet'']
          %} {{ is_state(''input_select.ambience'', ''Day'') and room in rooms }}

          '
      sequence:
      - service: light.turn_on
        data_template:
          entity_id: 'light.{{ trigger.to_state.object_id[:-7] }}

            '
    - conditions:
        condition: template
        value_template: '{% set room = trigger.to_state.object_id[:-7] %} {% set rooms
          = [''landing'', ''bathroom'', ''toilet'', ''patio''] %} {{ is_state(''input_select.ambience'',
          ''Night'') and room in rooms }}

          '
      sequence:
      - service: light.turn_on
        data_template:
          entity_id: '{% set room = trigger.to_state.object_id[:-7] %} light.{% if
            room == ''bathroom'' %}mirror{% else %}{{ room }}{% endif %}

            '
  - service: timer.start
    data_template:
      duration: 00:02:00
      entity_id: '{% set room = trigger.to_state.object_id[:-7] %} timer.{% if room
        == ''basement_stairs'' %}basement_hall{% else %}{{ room }}{% endif %}

        '
  id: 8943aecffe7545f1a65cf7746791165b
- alias: Turn off lights
  trigger:
  - platform: event
    event_type: timer.finished
  mode: parallel
  condition:
    - condition: not
      conditions:
        - condition: template
          value_template: "{{ trigger.to_state.object_id[:-7] == 'patio' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ is_state(''input_select.ambience'', ''Ambient'') }}'
      sequence:
      - service: light.turn_off
        data_template:
          entity_id: '{% set room = trigger.event.data.entity_id.split(''.'', 1)[1]
            %} {% set rooms = [''lounge'', ''hallway'', ''kitchen'', ''bedroom'',
            ''snug'', ''drawing_room''] %} light.{{ room }}{% if room in rooms %}_lamp{%
            endif %}

            '
    - conditions:
        condition: template
        value_template: '{{ states(''input_select.ambience'') in [''Bright'', ''Day'',
          ''Evening''] }}'
      sequence:
      - service: light.turn_off
        data_template:
          entity_id: '{% set room = trigger.event.data.entity_id.split(''.'', 1)[1]
            %} light.{{ room }}

            '
    - conditions:
        condition: template
        value_template: '{% set room = trigger.event.data.entity_id.split(''.'', 1)[1]
          %} {% set rooms = [''landing'', ''bathroom'', ''toilet'', ''patio''] %}
          {{ is_state(''input_select.ambience'', ''Night'') and room in rooms }}

          '
      sequence:
      - service: light.turn_off
        data_template:
          entity_id: '{% set room = trigger.event.data.entity_id.split(''.'', 1)[1]
            %} light.{% if room == ''bathroom'' %}mirror{% else %}{{ room }}{% endif
            %}

            '
  id: d1ef04ebbd7e46d5a40349a0344de3f6
- alias: Set Ambience to Day
  trigger:
  - event: sunrise
    platform: sun
  action:
  - data:
      entity_id: input_select.ambience
      option: Day
    service: input_select.select_option
  mode: single
  id: fad1aa9213cd4508ad2cee252b0151e0
- alias: Set Ambience to Evening
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      entity_id: input_select.ambience
      option: Evening
    service: input_select.select_option
  mode: single
  id: 5dd55f812aa8446588f5b6d1b08921d3
- id: '1596880408095'
  alias: Turn on back door light when motion detected
  trigger:
  - entity_id: binary_sensor.patio_motion
    platform: state
    to: 'on'
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - entity_id: light.back_door
    service: light.turn_on
  - entity_id: timer.patio
    service: timer.start
  mode: single
- id: '1596880578933'
  alias: Turn off back door light when there is no motion
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.patio
  action:
  - entity_id: light.back_door
    service: light.turn_off
  mode: single
