#Start of dwains-theme necessary code#
homeassistant:
  # If you want to customize entries with friendly_name or custom icon.
  # Read more here: https://www.home-assistant.io/docs/configuration/customizing-devices/
  # Uncomment line below and create file customize.yaml or edit it
  customize: !include customize.yaml

  # Below entry links to the packages folder required for Dwains Theme
  packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme

  # If you had any important strings before in homeassistant: place them back here below
  # 
#End of dwains-theme necessary code#

# Default config to bring in standard component set
automation: !include automations.yaml
cloud:
config:
history:
logbook:
logger:
  default: error
  logs:
    custom_components.unifiprotect: debug
map:
  entities:
   - device_tracker.claires_iphone
   - device_tracker.moto_g_7
   - sensor.moto_g_7_geocoded_location
  hours_to_show: 72
  dark_mode: true
mobile_app:
person:
script: !include scripts.yaml
sensor: !include sensors.yaml
ssdp:
sun:
system_health:
updater:
zeroconf:
zone:
input_boolean: !include input_boolean.yaml
input_datetime:
input_text:
input_number:
input_select: !include input_selects.yaml
  
# History
recorder:
  purge_keep_days: 45

# Discover some devices automatically
discovery:

# Alexa media
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.co.uk

# Bad Nest
badnest:
  user_id: !secret badnest_id
  access_token: !secret badnest_access_token
  region: eu

climate:
  - platform: badnest
    scan_interval: 10

# Spotify
spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret

# Media players
media_player:
  - platform: squeezebox
    host: 192.168.1.86
  - platform: squeezebox
    host: 192.168.1.120

# Google Calendar
google:
  client_id: !secret google_clientid
  client_secret: !secret google_client_secret

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Side bar configuration
panel_iframe:
  tasmota:
    title: 'TasmoAdmin'
    icon: mdi:lightbulb
    url: 'https://tasmota.andisoft.co.uk'
  squeezbox:
    title: 'SqueezeBox'
    icon: mdi:music
    url: 'https://squeezebox.andisoft.co.uk'
  brewblox:
    title: 'BrewBlox'
    icon: mdi:beer
    url: 'https://brewery.northsouthbrewing.co.uk'

#Weather
weather:
  - platform: darksky
    api_key: 82c93da6430dbe755461f4e4a9c20e3e
    name: stockport
    mode: daily

# Notifications
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_secret
    name: pushbullet
  - platform: alexa_media
    name: alexa_media

# Timers
timer: !include timers.yaml

# Camera
stream:
ffmpeg:

# MySensors 
mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      persistence_file: '/config/mysensors.json'
      baud_rate: 115200
  optimistic: false
  persistence: true
  retain: true
  version: '2.3'

# Alarm control panel
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: 2705
    trigger_time: 300
    arming_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 0
    armed_away:
      arming_time: 60
      delay_time: 30

# Sonoff
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  reload: always  # update device list every time HA starts
  devices:
    100032bd73:
      device_class: [light,light,light,light]
      name: Basement Lights 1
    100032a00d:
      device_class: [light,light,light,light]
      name: Basement Lights 2
    100032907e:
      device_class: [light,light,light,light]
      name: Outside Lights

# Lights
light:
  - platform: group
    name: Yeelights
    entities:
      - light.yeelight_color1_7c49eb12a895
      - light.yeelight_color1_04cf8caff0a4
      - light.yeelight_color1_7c49eb139475
      - light.yeelight_color1_04cf8caff23d
      - light.yeelight_color1_7c49eb138ddc
  - platform: group
    name: Inside
    entities:
      - light.yeelight_color1_7c49eb12a895
      - light.yeelight_color1_04cf8caff0a4
      - light.yeelight_color1_7c49eb139475
      - light.yeelight_color1_04cf8caff23d
      - light.yeelight_color1_7c49eb138ddc

circadian_lighting:

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.kitchen_lamp
      - light.drawing_room_lamp
      - light.lounge_lamp
      - light.bedroom_lamp
      - light.cellar_stairs
      - light.snug_lamp

binary_sensor:
  - platform: mqtt
    name: "Patio Motion"
    state_topic: "cameras/patio/motion"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "motion"

speedtestdotnet:
  scan_interval:
    minutes: 5
  monitored_conditions:
    - ping
    - download
    - upload

withings:
  client_id: !secret withings_clientid
  client_secret: !secret withings_secret
  profiles:
    - Andy
    - Claire