#Start of dwains-theme necessary code#
homeassistant:
  # If you want to customize entries with friendly_name or custom icon.
  # Read more here: https://www.home-assistant.io/docs/configuration/customizing-devices/
  # Uncomment line below and create file customize.yaml or edit it
  customize: !include customize.yaml
  packages: !include_dir_named packages

  # Below entry links to the packages folder required for Dwains Theme
  #packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme

  # If you had any important strings before in homeassistant: place them back here below
  #
#End of dwains-theme necessary code#
http:
  use_x_forwarded_for: true # To ensure HA understands that client requests come via reverse proxy
  trusted_proxies:
    - 172.30.32.0/23 # In Hass.io we need to add the Docker subnet

# Default config to bring in standard component set
automation: !include automations.yaml
button:
cloud:
config:
counter:
energy:
group: !include groups.yaml
history:
input_boolean:
input_datetime:
input_text:
input_number:
input_select:
logbook:
logger:
  default: critical
  logs:
    homeassistant.components.samsungtv: debug
    homeassistant.components.samsungtvws: debug
    samsungtvws.remote: debug
    #homeassistant.components.automation: debug
map:
  entities:
    - device_tracker.claires_iphone
    - device_tracker.moto_g_7
    - sensor.moto_g_7_geocoded_location
  hours_to_show: 72
  dark_mode: true
media_source:
mobile_app:
my:
person:
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
ssdp:
sun:
system_health:
timer:
zeroconf:
zone:

# History
recorder:
  purge_keep_days: 45

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# Alexa media
# alexa_media:
#   accounts:
#     - email: !secret amazon_user
#       password: !secret amazon_password
#       url: amazon.co.uk

# Spotify
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

# Bad Nest
# badnest:
#   user_id: !secret badnest_id
#   access_token: !secret badnest_access_token
#   region: eu

# climate:
#   - platform: badnest
#     scan_interval: 10

# Spotify
spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret

# Google Calendar
google:
  client_id: !secret google_clientid
  client_secret: !secret google_client_secret

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#Weather
weather:
  - platform: darksky
    api_key: 82c93da6430dbe755461f4e4a9c20e3e
    name: stockport
    mode: daily

# Notifications
notify:
  - name: Phones
    platform: group
    services:
      - service: mobile_app_andrews_iphone
      - service: mobile_app_claires_iphone
  - name: alexa_media
    platform: alexa_media

# Camera
stream:
ffmpeg:

# Neato
neato:
  client_id: !secret neato_clientid
  client_secret: !secret neato_secret

# Alarm control panel
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: 2705
    trigger_time: 300
    arming_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 0
    armed_away:
      arming_time: 60
      delay_time: 30

# Sonoff
# sonoff:
#   username: !secret sonoff_username
#   password: !secret sonoff_password
#   mode: local
#   reload: always  # update device list every time HA starts
#   devices:
#     1000bab381:
#       device_class: [light,light,light,light]
#       name: Upstairs Lights 1
#     1000bab6de:
#       device_class: [light,light,light,light]
#       name: Upstairs Lights 2
#     100032907e:
#       device_class: [light,light,light,light]
#       name: Outside Lights
#     1000ba9977:
#       device_class: [light,light,light,light]
#       name: Downstairs Lights 1
#     1000bab17a:
#       device_class: [light,light,light,light]
#       name: Downstairs Lights 2
#     100032bd73:
#       device_class: [light,light,light,light]
#       name: Basement Lights 1
#     100032a00d:
#       device_class: [light,light,light,light]
#       name: Basement Lights 2

# Lights
yeelight:
  # devices:
  #   192.168.30.17:
  #     name: Snug Floor Lamp
  #   192.168.30.43:
  #     name: Bedside Lamp
  #   192.168.30.48:
  #     name: Breakfast Bar Lamp
  #   192.168.30.106:
  #     name: Hallway Lamp
  #   192.168.30.171:
  #     name: Lounge Floor Room Lamp
  #   192.168.30.200:
  #     name: Lounge Corner Lamp

binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptime_key
template: !include templates.yaml

withings:
  client_id: !secret withings_clientid
  client_secret: !secret withings_secret
  use_webhook: true

entity_controller: !include entity_controller.yaml

influxdb:
  host: 192.168.1.1
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  exclude:
    domains:
      - automation
      - script
      - persistent_notification
  tags:
    instance: prod
    source: hass
