#Start of dwains-theme necessary code#
homeassistant:
  # If you want to customize entries with friendly_name or custom icon.
  # Read more here: https://www.home-assistant.io/docs/configuration/customizing-devices/
  # Uncomment line below and create file customize.yaml or edit it
  customize: !include customize.yaml

  # Below entry links to the packages folder required for Dwains Theme
  #packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme

  # If you had any important strings before in homeassistant: place them back here below
  #
#End of dwains-theme necessary code#

# Default config to bring in standard component set
automation: !include automations.yaml
cloud:
config:
group: !include groups.yaml
history:
logbook:
logger:
  default: critical
  #logs:
    #custom_components.entity_controller: debug
map:
  entities:
    - device_tracker.claires_iphone
    - device_tracker.moto_g_7
    - sensor.moto_g_7_geocoded_location
  hours_to_show: 72
  dark_mode: true
mobile_app:
my:
person:
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
ssdp:
sun:
system_health:
updater:
zeroconf:
zone:
input_boolean:
input_datetime:
input_text:
input_number:
input_select:

# History
recorder:
  purge_keep_days: 45

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# Alexa media
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.co.uk

# Bad Nest
# badnest:
#   user_id: !secret badnest_id
#   access_token: !secret badnest_access_token
#   region: eu

# climate:
#   - platform: badnest
#     scan_interval: 10

# Spotify
spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret

# Google Calendar
google:
  client_id: !secret google_clientid
  client_secret: !secret google_client_secret

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Side bar configuration
panel_iframe:
  fermentrack:
    title: 'Fermentrack'
    icon: mdi:beer
    url: 'https://track.northsouthbrewing.co.uk'
  # tasmota:
  #   title: 'TasmoAdmin'
  #   icon: mdi:lightbulb
  #   url: 'https://tasmota.andisoft.co.uk'
  # squeezbox:
  #   title: 'SqueezeBox'
  #   icon: mdi:music
  #   url: 'https://squeezebox.andisoft.co.uk'

#Weather
weather:
  - platform: darksky
    api_key: 82c93da6430dbe755461f4e4a9c20e3e
    name: stockport
    mode: daily

# Notifications
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_secret
    name: pushbullet
  - platform: alexa_media
    name: alexa_media

# Timers
timer:

# Camera
stream:
ffmpeg:

# Neato
neato:
  client_id: !secret neato_clientid
  client_secret: !secret neato_secret

# Alarm control panel
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: 2705
    trigger_time: 300
    arming_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 0
    armed_away:
      arming_time: 60
      delay_time: 30

# Sonoff
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  reload: always  # update device list every time HA starts
  devices:
    1000bab381:
      device_class: [light,light,light,light]
      name: Upstairs Lights 1
    1000bab6de:
      device_class: [light,light,light,light]
      name: Upstairs Lights 2
    100032907e:
      device_class: [light,light,light,light]
      name: Outside Lights
    1000ba9977:
      device_class: [light,light,light,light]
      name: Ground Floor Lights 1
    1000bab17a:
      device_class: [light,light,light,light]
      name: Ground Floor Lights 2
    100032bd73:
      device_class: [light,light,light,light]
      name: Basement Lights 1
    100032a00d:
      device_class: [light,light,light,light]
      name: Basement Lights 2

# Lights
yeelight:
  # devices:
  #   192.168.30.17:
  #     name: Snug Lamp
  #   192.168.30.43:
  #     name: Bedroom Lamp
  #   192.168.30.48:
  #     name: Kitchen Lamp
  #   192.168.30.106:
  #     name: Hallway Lamp
  #   192.168.30.171:
  #     name: Drawing Room Lamp
  #   192.168.30.200:
  #     name: Lounge Lamp

light:
  - platform: group
    name: Yeelights
    entities:
      - light.kitchen_lamp
      - light.drawing_room_lamp
      - light.lounge_lamp
      - light.hall_lamp
      - light.bedroom_lamp
      - light.basement_stairs
      - light.snug_lamp
  - platform: group
    name: Basement Lights
    entities:
      - light.basement_hall
      - light.snug
      - light.snug_lamp
      - light.dining_room
      - light.toilet
      - light.utility_room
      - light.brewery
  - platform: group
    name: Ground Floor Lights
    entities:
      - light.hallway
      - light.hallway_lamp
      - light.lounge
      - light.lounge_lamp
      - light.drawing_room
      - light.drawing_room_lamp
      - light.kitchen
      - light.kitchen_lamp
  - platform: group
    name: Upstairs Lights
    entities:
      - light.landing
      - light.studio
      - light.bathroom
      - light.mirror
      - light.bedroom
      - light.bedroom_lamp
      - light.guest_room
      - light.dressing_room
  - platform: group
    name: Inside Lights
    entities:
      - light.basement_lights
      - light.ground_floor_lights
      - light.upstairs_lights
  - platform: group
    name: Outside Lights
    entities:
      - light.porch
      - light.cellar_door
      - light.back_door
      - light.patio
  - platform: group
    name: Garden Lights
    entities:
      - light.cellar_door
      - light.back_door
      - light.patio
  - platform: group
    name: All Lights
    entities:
      - light.inside_lights
      - light.outside_lights

circadian_lighting:

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.kitchen_lamp
      - light.drawing_room_lamp
      - light.lounge_lamp
      - light.hall_lamp
      - light.bedroom_lamp
      - light.basement_stairs
      - light.snug_lamp

binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptime_key
  - platform: template
    sensors:
      patio_motion:
        friendly_name: "Patio Motion"
        value_template: "{{ is_state('input_boolean.patio_motion', 'on') }}"
        device_class: "motion"
  # - platform: mqtt
  #   name: "Patio Motion"
  #   state_topic: "cameras/patio/motion"
  #   payload_on: "ON"
  #   payload_off: "OFF"
  #   off_delay: 5
  #   device_class: "motion"

withings:
  client_id: !secret withings_clientid
  client_secret: !secret withings_secret
  use_webhook: true

entity_controller: !include entity_controller.yaml