#Start of dwains-theme necessary code#
homeassistant:
  # If you want to customize entries with friendly_name or custom icon.
  # Read more here: https://www.home-assistant.io/docs/configuration/customizing-devices/
  # Uncomment line below and create file customize.yaml or edit it
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config/www/tmp
    - /config/www/images

  # Below entry links to the packages folder required for Dwains Theme
  #packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme

  # If you had any important strings before in homeassistant: place them back here below
  #
#End of dwains-theme necessary code#
http:
  use_x_forwarded_for: true # To ensure HA understands that client requests come via reverse proxy
  trusted_proxies:
    - 172.30.32.0/23 # In Hass.io we need to add the Docker subnet

# Default config to bring in standard component set
automation: !include automations.yaml
button:
cloud:
config:
counter:
energy:
# frontend:
#   extra_module_url:
#     - /local/card-mod.js
group: !include groups.yaml
history:
input_boolean:
input_button:
input_datetime:
input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'
input_number:
input_select:
logbook:
logger:
  default: critical
map:
  entities:
    - device_tracker.claires_iphone
    - device_tracker.pixel_6_2
  hours_to_show: 72
  dark_mode: true
media_source:
mobile_app:
my:
person:
proximity:
  home:
    devices:
      - person.andy
      - person.claire
    tolerance: 10
    unit_of_measurement: mi
prometheus:
scene: !include scenes.yaml
schedule:
script: !include scripts.yaml
sensor: !include sensors.yaml
ssdp:
sun:
system_health:
timer:
zeroconf:
zone:

# History
recorder:
  purge_keep_days: 45

# Discover some devices automatically
# discovery:
#   ignore:
#     - yeelight

# Spotify
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Notifications
notify:
  - name: Phones
    platform: group
    services:
      - service: mobile_app_andrews_iphone
      - service: mobile_app_claires_iphone
  - name: alexa_media
    platform: alexa_media

# Camera
stream:
ffmpeg:

# Alarm control panel
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: 2705
    trigger_time: 300
    arming_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 0
    armed_away:
      arming_time: 60
      delay_time: 30

# Lights
yeelight:
  custom_effects:
    - name: "Lightning"
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - TemperatureTransition: [6500, 50, 0]
          - SleepTransition: [3000]
          - TemperatureTransition: [6500, 50, 50]
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - TemperatureTransition: [6500, 50, 0]
          - SleepTransition: [1500]
    - name: "Flicker"
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - SleepTransition: [3000]
    - name: "Flicker2"
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - SleepTransition: [3000]
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - TemperatureTransition: [6500, 500, 0]
          - TemperatureTransition: [6500, 50, 80]
    - name: "FlickerScare"
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - SleepTransition: [3000]
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - TemperatureTransition: [6500, 50, 0]
          - TemperatureTransition: [6500, 50, 50]
          - TemperatureTransition: [6500, 500, 0]
          - SleepTransition: [3000]
          - RGBTransition: [255, 0, 0, 50, 80]
          - SleepTransition: [10000]
    - name: "FlickerWarm"
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1700, 50, 0]
          - TemperatureTransition: [1700, 50, 50]
          - SleepTransition: [3000]
    - name: "FlickerWarmScare"
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1700, 50, 0]
          - TemperatureTransition: [1700, 50, 50]
          - SleepTransition: [3000]
          - TemperatureTransition: [1700, 50, 0]
          - TemperatureTransition: [1700, 50, 50]
          - TemperatureTransition: [1700, 50, 0]
          - TemperatureTransition: [1700, 50, 50]
          - TemperatureTransition: [1700, 500, 0]
          - SleepTransition: [3000]
          - RGBTransition: [255, 0, 0, 50, 80]
          - RGBTransition: [255, 0, 0, 50, 0]
          - SleepTransition: [10000]
    - name: "Self_Alarm"
      flow_params:
        count: 0
        transitions:
          - RGBTransition: [0, 0, 255, 300, 1]
          - RGBTransition: [222, 0, 0, 50, 1]
          - RGBTransition: [255, 52, 52, 50, 256]
          - RGBTransition: [222, 0, 0, 50, 1]
          - RGBTransition: [0, 0, 255, 50, 256]
          - RGBTransition: [222, 0, 0, 50, 1]
          - RGBTransition: [255, 52, 52, 50, 256]
          - RGBTransition: [222, 0, 0, 50, 1]
    - name: "Fire Flicker"
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition: [1000]

#binary_sensor:
#- platform: uptimerobot
# api_key: !secret uptime_key
template: !include templates.yaml

entity_controller: !include entity_controller.yaml

influxdb:
  host: 192.168.1.1
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  exclude:
    domains:
      - automation
      - script
      - persistent_notification
  tags:
    instance: prod
    source: hass

waste_collection_schedule:
  sources:
    - name: stockport_gov_uk
      args:
        uprn: "200000779202"
      customize:
        - type: Black bin
          picture: /local/images/black-bin.png
        - type: Brown bin
          picture: /local/images/brown-bin.png
        - type: Blue bin
          picture: /local/images/blue-bin.png
        - type: Green bin
          picture: /local/images/green-bin.png
