#- platform: nest
#  monitored_conditions:
#    - "temperature"
#    - "target"
#    - "humidity"
#    - "weather_temperature"
#    - "weather_humidity"
#    - "weather_condition"
#    - "wind_speed"
#    - "wind_direction"

# Waste sensors
- platform: waste_collection_schedule
  name: Black bin
  details_format: appointment_types
  add_days_to: True
  value_template: "{{ value.daysTo }}"
  types:
    - Black bin
- platform: waste_collection_schedule
  name: Brown bin
  details_format: appointment_types
  add_days_to: True
  value_template: "{{ value.daysTo }}"
  types:
    - Brown bin
- platform: waste_collection_schedule
  name: Blue bin
  details_format: appointment_types
  add_days_to: True
  value_template: "{{ value.daysTo }}"
  types:
    - Blue bin
- platform: waste_collection_schedule
  name: Green bin
  details_format: appointment_types
  add_days_to: True
  value_template: "{{ value.daysTo }}"
  types:
    - Green bin

#platform: dnsip
#platform: dnsip
  #hostname: home.andisoft.co.uk
  #name: hass
  #resolver: 8.8.8.8
# Light state overrides

# # Hallway light
# - platform: template
#   sensors:
#     hallway_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Evening'] and is_state('light.hallway_lamp', 'off')) }}

# # Hallway lamp
# - platform: template
#   sensors:
#     hallway_lamp_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Ambient', 'Evening'] and is_state('light.hallway', 'off')) }}

# # Lounge light
# - platform: template
#   sensors:
#     lounge_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Evening'] and is_state('input_select.lounge_mode', 'Normal') and is_state('light.lounge_corner_lamp', 'off')) }}

# # Lounge Corner lamp
# - platform: template
#   sensors:
#     lounge_corner_lamp_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Ambient', 'Evening'] and is_state('input_select.lounge_mode', 'Normal') and is_state('light.lounge', 'off')) }}

# # Drawing Room light
# - platform: template
#   sensors:
#     drawing_room_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Evening'] and is_state('light.bookshelf', 'off')) }}

# # Bookshelf light
# - platform: template
#   sensors:
#     bookshelf_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Ambient', 'Evening'] and is_state('light.drawing_room', 'off')) }}

# # Lounge Floor lamp
# - platform: template
#   sensors:
#     lounge_floor_lamp_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Ambient', 'Evening'] and is_state('input_select.lounge_mode', 'Normal') and is_state('light.lounge', 'off')) }}

# # Kitchen light
# - platform: template
#   sensors:
#     kitchen_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Evening'] and is_state('light.breakfast_bar_lamp', 'off')) }}

# # Breakfast Bar lamp
# - platform: template
#   sensors:
#     breakfast_bar_lamp_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Ambient', 'Evening'] and is_state('light.kitchen', 'off')) }}

# # Bathroom light
# - platform: template
#   sensors:
#     bathroom_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Evening'] and is_state('light.mirror', 'off')) }}

# # Mirror light
# - platform: template
#   sensors:
#     mirror_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Ambient', 'Evening', 'Night'] and is_state('light.bathroom', 'off')) }}

# # Snug light
# - platform: template
#   sensors:
#     snug_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Day'] and is_state('input_select.snug_mode', 'Normal') and is_state('light.snug_floor_lamp', 'off')) }}

# # Snug Floor lamp
# - platform: template
#   sensors:
#     snug_floor_lamp_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Ambient', 'Evening'] and is_state('input_select.snug_mode', 'Normal') and is_state('light.snug', 'off')) }}

# # Dining Room light
# - platform: template
#   sensors:
#     dining_room_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Day', 'Evening']) }}

# # Basement Hall light
# - platform: template
#   sensors:
#     basement_hall_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Day', 'Evening']) }}

# # Utility Room light
# - platform: template
#   sensors:
#     utility_room_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Day', 'Evening']) }}

# # Toilet light
# - platform: template
#   sensors:
#     toilet_light_constrained:
#       value_template: >-
#         {{ not (states('input_select.ambience') in ['Bright', 'Day', 'Evening', 'Night']) }}

#Mqtt Presense Sensors
# - platform: mqtt_room
#   device_id: "tile:cd1dcb7ae277"
#   name: "Claire Keys Tile Ble"
#   state_topic: "espresense/devices/tile:cd1dcb7ae277"
#   timeout: 60
#   away_timeout: 120
# - platform: mqtt_room
#   device_id: "tile:e572c53969ee"
#   name: "Andy Keys Tile Ble"
#   state_topic: "espresense/devices/tile:e572c53969ee"
#   timeout: 60
#   away_timeout: 120
# - platform: mqtt_room
#   device_id: "tile:cd1dcb7ae277"
#   name: "Car Keys Tile Ble"
#   state_topic: "espresense/devices/tile:cd1dcb7ae277"
#   timeout: 60
#   away_timeout: 120
# - platform: mqtt_room
#   device_id: "apple:1005:9-12"
#   name: "Andy IPhone Ble"
#   state_topic: "espresense/devices/apple:1005:9-12"
#   timeout: 60
#   away_timeout: 120
# - platform: mqtt_room
#   device_id: "apple:1006:10-12"
#   name: "Claire IPhone Ble"
#   state_topic: "espresense/devices/apple:1006:10-12"
#   timeout: 60
#   away_timeout: 120
# - platform: mqtt_room
#   device_id: "apple:1005:9-26"
#   name: "Claire IWatch Ble"
#   state_topic: "espresense/devices/apple:1005:9-26"
#   timeout: 60
#   away_timeout: 120
# Energy
# - platform: integration
#   source: sensor.bulb_energy_meter_gas_meter
#   name: gas meter
#   unit_prefix: k
#   unit_time: h
#   round: 2
