# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host:
  port: 1883
  ssl: false
  username:
  password:

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

# Floors w/ the points to draw it in meters
floors:
  - id: upstairs
    name: Upstairs
    bounds: [[-0.5, -1, 3], [6, 13, 6]]
    rooms:
      - name: Guest Room
        points:
          - [0, 11.36]
          - [4.15, 11.36]
          - [4.15, 7.75]
          - [0, 7.75]
          - [0, 8.5]
          - [0.37, 8.5]
          - [0.37, 10.57]
          - [0, 10.57]
          - [0, 11.36]
      - name: Bedroom
        points:
          - [0, 7.75]
          - [3.94, 7.75]
          - [3.94, 4.3]
          - [0, 4.3]
          - [0, 5.1]
          - [0.37, 5.1]
          - [0.37, 6.13]
          - [0, 6.13]
          - [0, 7.75]
      - name: Landing
        points:
          - [4.15, 11.36]
          - [5.55, 11.36]
          - [5.55, 4.31]
          - [3.94, 4.31]
          - [3.94, 7.75]
          - [4.15, 7.75]
          - [4.15, 11.36]
      - name: Studio
        points:
          - [5.55, 4.31]
          - [2.25, 4.31]
          - [2.25, 0]
          - [5.55, 0]
          - [5.55, 0.95]
          - [5.05, 0.95]
          - [5.05, 2.87]
          - [5.47, 2.87]
          - [5.47, 3.34]
          - [5.55, 3.34]
          - [5.55, 4.31]

  - id: downstairs
    name: Downstairs
    bounds: [[-0.5, -1, 0], [6, 13, 2.9]]
    rooms:
      - name: Lounge
        points:
          - [0, 12.27]
          - [2.88, 12.27]
          - [2.88, 11.36]
          - [4.15, 11.36]
          - [4.15, 7.75]
          - [0, 7.75]
          - [0, 8.5]
          - [0.37, 8.5]
          - [0.37, 10.57]
          - [0, 10.57]
          - [0, 12.27]
      - name: Drawing Room
        points:
          - [0, 7.75]
          - [3.94, 7.75]
          - [3.94, 4.3]
          - [0, 4.3]
          - [0, 5.1]
          - [0.37, 5.1]
          - [0.37, 6.13]
          - [0, 6.13]
          - [0, 7.75]
      - name: Hallway
        points:
          - [4.15, 11.36]
          - [5.55, 11.36]
          - [5.55, 4.31]
          - [3.94, 4.31]
          - [3.94, 7.75]
          - [4.15, 7.75]
          - [4.15, 11.36]
      - name: Kitchen
        points:
          - [5.55, 4.31]
          - [2.25, 4.31]
          - [2.25, 0]
          - [5.55, 0]
          - [5.55, 0.95]
          - [5.05, 0.95]
          - [5.05, 2.87]
          - [5.47, 2.87]
          - [5.47, 3.34]
          - [5.55, 3.34]
          - [5.55, 4.31]

# Locations of espresense nodes in meters
nodes:
  - name: lounge
    point: [0.15, 11.87, 1]
    floors: ["downstairs"]
  - name: kitchen
    point: [5.40, 0, 1]
    floors: ["downstairs"]
  - name: studio
    point: [5.45, 0.15, 3.7]
    floors: ["upstairs"]

# Devices to track
devices:
  #  - id: "*" # Track all devices
  - name: "*" # Track all named devices
  # - id: darrells-watch
  #   name: Darrell's Watch
  # - id: darrells-iphone
  #   name: Darrell's iPhone
