LightControl:
  Rooms:
    - DrawingRoom:
        MotionLights:
            - DrawingRoomLight:
                Motion: binary_sensor.drawingroom_motion
                Light: light.drawingroom
                Timeout: 120
                Backoff: 1.1
                MaxBackoff: 300
            - BookshelfLight:
                Motion: binary_sensor.drawingroom_motion
                Light: light.bookshelf
                Ambient: true
                Timeout: 120
                Backoff: 1.1
                MaxBackoff: 300
    - Lounge:
        MotionLights:
            - LoungeLight:
                Motion: binary_sensor.lounge_motion
                Light: light.lounge
                Timeout: 120
                Backoff: 1.1
                MaxBackoff: 300
            - LoungeCornerLamp:
                Motion: binary_sensor.lounge_motion
                Light: light.lounge_corner_lamp
                Ambient: true
                Timeout: 120
                Backoff: 1.1
                MaxBackoff: 300
            - LoungeFloorLamp:
                Motion: binary_sensor.lounge_motion
                Light: light.lounge_floor_lamp
                Ambient: true
                Timeout: 120
                Backoff: 1.1
                MaxBackoff: 300
    - Hallway:
        MotionLights:
            - HallwayLight:
                Motion: binary_sensor.hallway_motion
                Light: light.hallway
                Timeout: 60
                Backoff: 1.1
                MaxBackoff: 150
            - HallwayLamp:
                Motion: binary_sensor.hallway_motion
                Light: light.hallway_lamp
                Ambient: true
                Timeout: 60
                Backoff: 1.1
                MaxBackoff: 150
    - Kitchen:
        MotionLights:
            - KitchenLight:
                Motion: binary_sensor.kitchen_motion
                Light: light.kitchen
                Timeout: 90
                Backoff: 1.2
                MaxBackoff: 180
            - HallwayLamp:
                Motion: binary_sensor.kitchen_motion
                Light: light.breakfast_bar_lamp
                Ambient: true
                Timeout: 90
                Backoff: 1.2
                MaxBackoff: 180