- alias: Basement Hall Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.basement_hall_light_contrained
    - input_select.ambience
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Bright'',
          ''Day'', ''Evening'']) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.basement_hall_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.basement_hall_light_constrained
  mode: single
  id: 170b8023063a4f83b9aba8cd0771a2d4
- id: '1622719466285'
  alias: Turn on basement hall lights when electric cabinet door is open
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 879be2aff99b3b5eb4f25bc6e00bcb62
    entity_id: binary_sensor.electric_cabinet_door_contact
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.basement_hall
  mode: single
- id: '1622719668545'
  alias: Turn off basement hall light when electric cabinet door closed
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 879be2aff99b3b5eb4f25bc6e00bcb62
    entity_id: binary_sensor.electric_cabinet_door_contact
    domain: binary_sensor
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.basement_hall
  mode: single