- alias: Bathroom Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.bathroom_light_contrained
    - input_select.ambience
    - light.mirror
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Bright'',
          ''Evening''] and is_state(''light.mirror'', ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bathroom_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bathroom_light_constrained
  mode: single
  id: f15e5f50e4aa43da84d66f16ea6b95cf
- alias: Mirror Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.mirror_light_contrained
    - input_select.ambience
    - light.bathroom
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Ambient'',
          ''Evening'', ''Night''] and is_state(''light.bathroom'', ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.mirror_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.mirror_light_constrained
  mode: single
  id: c22b53b755fd48b7b10dcba5bfdc3018
- id: '1619549518704'
  alias: Shower timer start
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.in_shower
    state: 'true'
  action:
  - service: timer.start
    data:
      duration: '600'
  mode: restart
- id: '1619550242949'
  alias: Shower timer finished
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.shower
  condition:
  - condition: state
    entity_id: input_boolean.in_shower
    state: 'true'
  action:
  - service: light.turn_off
    target:
      area_id: cc4d1282baa64200a75e9347f5f87bdb
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.in_shower
  mode: single