- alias: Bedroom Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.bedroom_light_contrained
    - input_select.ambience
    - light.bedroom_lamp
    - input_boolean.in_bed
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Bright'',
          ''Evening''] and is_state(''light.bedroom_lamp'', ''off'') and is_state(''input_boolean.in_bed'',
          ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedroom_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_light_constrained
  mode: single
  id: 18c5d98e6cd945ea8089ea36abe3049f
- alias: Bedroom Lamp Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.bedroom_lamp_contrained
    - input_select.ambience
    - light.bedroom
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Ambient'',
          ''Evening''] and is_state(''light.bedroom'', ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedroom_lamp_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_lamp_constrained
  mode: single
  id: e6e53418e5474b03b92123912e18fdd3
- id: '1624467229490'
  alias: In bed
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.in_bed
    to: 'on'
    for: 00:05:00
  condition:
  - condition: time
    after: '20:00:00'
    before: 04:30:00
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.in_bed
  mode: single
- id: '1624870805960'
  alias: Out of bed
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.in_bed
    to: 'off'
    for: 00:05:00
  condition:
  - condition: time
    after: 05:00:00
    before: '12:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.in_bed
  mode: single