- alias: Dining Room Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.dining_room_light_contrained
    - input_select.ambience
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Bright'',
          ''Day'', ''Evening'']) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dining_room_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.dining_room_light_constrained
  mode: single
  id: 4b6ac44609014c3a8c0127ffaa9e0a9f