- alias: Drawing Room Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.drawing_room_light_constrained
    - input_select.ambience
    - light.bookshelf
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Bright'',
          ''Evening''] and is_state(''light.bookshelf'', ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.drawing_room_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.drawing_room_light_constrained
  mode: single
  id: 93bda13f503c4f5780004a4cdcf1b1ea
- alias: Bookshelf Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.bookshelf_light_contrained
    - input_select.ambience
    - light.drawing_room
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Ambient'',
          ''Evening''] and is_state(''light.drawing_room'', ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bookshelf_light_contrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bookshelf_light_contrained
  mode: single
  id: 1dd62d0407af4ba68939726a92353417