- alias: Guest Room Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_select.ambience
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Ambient'',
          ''Evening'']) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_room_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_room_light_constrained
  mode: single
  id: f6d3b5116682406888bd5ffc772efe81