- alias: Hallway Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.hallway_light_contrained
    - input_select.ambience
    - light.hallway_lamp
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Bright'',
          ''Evening''] and is_state(''light.hallway_lamp'', ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.hallway_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.hallway_light_constrained
  mode: single
  id: 5b1af16edd2f419ab2a006d2615e3db2
- alias: Hallway Lamp Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.hallway_light_contrained
    - input_select.ambience
    - light.hallway
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Ambient'',
          ''Evening''] and is_state(''light.hallway'', ''off'')) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.hallway_lamp_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.hallway_lamp_constrained
  mode: single
  id: b03b0847981b4e1f87e1435b36758a8f
- id: '1622826722616'
  alias: Front door open after sunset
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: e87ea564142edf52ebc5fb9d015444ed
    entity_id: binary_sensor.front_door_contact
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    after_offset: -00:30:00
  action:
  - service: light.turn_on
    target:
      entity_id: light.hallway
  mode: single
- id: '1622826801223'
  alias: Front door closed after sunset
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: e87ea564142edf52ebc5fb9d015444ed
    entity_id: binary_sensor.front_door_contact
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    after_offset: -00:30:00
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.hallway
  mode: single