- alias: Studio Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_select.ambience
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Ambient'',
          ''Evening''])}}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.studio_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.studio_light_constrained
  mode: single
  id: 7119d64911784af3a51dfe8e3a058989
