- alias: Toilet Light Constrained
  trigger:
  - platform: state
    entity_id:
    - input_boolean.toilet_light_contrained
    - input_select.ambience
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not (states(''input_select.ambience'') in [''Bright'',
          ''Day'', ''Evening'', ''Ambient'']) }}'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.toilet_light_constrained
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.toilet_light_constrained
  mode: single
  id: f7ad91532b454991b258ed726b18c562