 # https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/global.html
 
 # I prefer using darksky as my weather component.
 # use the weather component and not (only) the darksky sensor! Read here: https://www.home-assistant.io/integrations/weather.darksky/
 # Some people only have the DarkSky sensor and not the weather setup or visa versa.
 # Please make sure you got it right!!!!!
 # If you want to use darksky, make sure you USE THIS: https://www.home-assistant.io/integrations/weather.darksky/
 # AND USE THIS: https://www.home-assistant.io/integrations/darksky/
 # So make sure you got both installed! It's not the same!

global:
  language: en
  outside_temperature: sensor.garden_temperature
  outside_humidity: sensor.garden_relative_humidity
  inside_temperature: climate.downstairs #Can be climate. or sensor. entity
  weather: weather.stockport # Configure a weather entity!
  alarm: alarm_control_panel.alarm #Alarm panel entity
