# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Porch
    icon: mdi:key-outline
    light: light.sonoff_100032907e_3
    addons:
      - name: Doorbell
        icon: mdi:bell-outline
        path: 'dwains-theme/addons/rooms/hello-room/page.yaml'
        button_path: 'dwains-theme/addons/rooms/hello-room/button.yaml'
        data:
          some_data: 'This is some data parsed.'
          some_other_data: 'and some other data.'
          entity: binary_sensor.doorbell_button
  - name: Hallway
    icon: mdi:view-agenda-outline
    media_player: media_player.hall_tablet_s_alexa_apps
    motion: binary_sensor.hall_motion
  - name: Lounge
    icon: mdi:sofa
    light: light.yeelight_color1_7c49eb139475
    motion: binary_sensor.lounge_motion
    media_player: media_player.lounge_echo_plus
    climate: climate.downstairs
    humidity: climate.downstairs_thermostat_humidity
    temperature: sensor.downstairs_thermostat_temperature
  - name: Drawing Room
    icon: mdi:fireplace
    media_player: media_player.drawing_room_echo_dot
    light: light.yeelight_color1_04cf8caff0a4
    motion: binary_sensor.drawing_room_motion
  - name: Kitchen
    icon: mdi:fridge-outline
    light: light.yeelight_color1_7c49eb12a895
    media_player: media_player.kitchen_echo_show
    motion: binary_sensor.kitchen_motion
    door: binary_sensor.patio_door
  - name: Patio
    icon: mdi:flower-outline
    light: light.sonoff_100032907e_1
    media_player: media_player.kitchen_echo_show
    motion: binary_sensor.patio_motion
    temperature: sensor.garden_temperature
    humidity: sensor.garden_relative_humidity
  - name: Studio
    icon: mdi:headphones
  - name: Bathroom
    icon: mdi:shower
  - name: Middle Bedroom
    icon: mdi:bed-double-outline
    light: light.yeelight_color1_04cf8caff23d
    media_player: media_player.bedroom_echo_spot
    climate: climate.upstairs
    humidity: climate.upstairs_thermostat_humidity
    temperature: sensor.upstairs_thermostat_temperature
  - name: Front Bedroom
    icon: mdi:bed-double
  - name: Dressing Room
    icon: mdi:tshirt-crew-outline
    media_player: media_player.dressing_room_echo_dot
  - name: Landing
    icon: mdi:stairs-up
    media_player: media_player.landing_tablet_s_alexa_apps
  - name: Basement Hall
    icon: mdi:stairs-down
    light: light.sonoff_100032bd73_3
    motion: binary_sensor.patio_motion
    media_player: media_player.lounge_echo_plus
  - name: Electric Cabinet
    icon: mdi:flash-outline
    light: light.sonoff_100032bd73_3
  - name: Snug
    icon: mdi:filmstrip
    light: light.sonoff_100032a00d_2
    motion: binary_sensor.snug_motion
    media_player: media_player.snug_echo_input
  - name: Dining Room
    icon: mdi:silverware-fork-knife
    light: light.sonoff_100032a00d_1
    motion: binary_sensor.dining_room_motion
    media_player: media_player.dining_room_echo_input
    climate: climate.basement
    humidity: climate.basement_thermostat_humidity
    temperature: sensor.basement_thermostat_temperature
    addons:
      - name: Printer
        icon: mdi:printer
        path: 'dwains-theme/addons/rooms/dining-room/printer/page.yaml'
        data:
          entity: sensor.brother_hl_3150cdw_series
  - name: Toliet
    icon: mdi:toilet
    light: light.sonoff_100032bd73_1
    motion: binary_sensor.toilet_motion
  - name: Utility Room
    icon: mdi:washing-machine
    light: light.sonoff_100032bd73_2
    motion: binary_sensor.utility_motion
    media_player: media_player.utility_room_echo_dot
  - name: Brewery
    icon: mdi:beer-outline
    light: light.sonoff_100032bd73_4