# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Porch
    icon: mdi:key-outline
    light: light.porch
    addons:
      - name: Doorbell
        icon: mdi:bell-outline
        path: 'dwains-theme/addons/rooms/hello-room/page.yaml'
        button_path: 'dwains-theme/addons/rooms/hello-room/button.yaml'
        data:
          some_data: 'This is some data parsed.'
          some_other_data: 'and some other data.'
          entity: binary_sensor.doorbell_button
  - name: Hallway
    icon: mdi:view-agenda-outline
    media_player: media_player.hall_tablet_s_alexa_apps
    motion: binary_sensor.hallway_motion
    light: group.hallway_lights
  - name: Lounge
    icon: mdi:sofa
    light: group.lounge_lights
    motion: binary_sensor.lounge_motion
    media_player: media_player.lounge_echo_plus
    climate: climate.downstairs
    humidity: climate.downstairs_thermostat_humidity
    temperature: sensor.downstairs_thermostat_temperature
  - name: Drawing Room
    icon: mdi:fireplace
    media_player: media_player.drawing_room_echo_dot
    light: group.drawing_room_lights
    motion: binary_sensor.drawing_room_motion
  - name: Kitchen
    icon: mdi:fridge-outline
    light: group.kitchen_lights
    media_player: media_player.kitchen_echo_show
    motion: binary_sensor.kitchen_motion
    door: binary_sensor.patio_door
  - name: Patio
    icon: mdi:flower-outline
    light: group.patio_lights
    media_player: media_player.kitchen_echo_show
    motion: binary_sensor.patio_motion
    temperature: sensor.garden_temperature
    humidity: sensor.garden_relative_humidity
  - name: Studio
    icon: mdi:headphones
    light: light.studio
    motion: binary_sensor.studio_motion
  - name: Bathroom
    icon: mdi:shower
    light: group.bathroom_lights
    motion: binary_sensor.bathroom_motion
  - name: Bedroom
    icon: mdi:bed-double-outline
    light: group.bedroom_lights
    motion: binary_sensor.bedroom_motion
    media_player: media_player.bedroom_echo_spot
    climate: climate.upstairs
    humidity: climate.upstairs_thermostat_humidity
    temperature: sensor.upstairs_thermostat_temperature
  - name: Guest Bedroom
    icon: mdi:bed-double
    light: light.guest_bedroom
    motion: binary_sensor.guest_bedroom_motion
  - name: Dressing Room
    icon: mdi:tshirt-crew-outline
    light: light.dressing_room
    motion: binary_sensor.dressing_room_motion
    media_player: media_player.dressing_room_echo_dot
  - name: Landing
    icon: mdi:stairs-up
    light: light.landing
    motion: binary_sensor.landing_motion
    media_player: media_player.landing_tablet_s_alexa_apps
  - name: Basement Hall
    icon: mdi:stairs-down
    light: group.basement_hall_lights
    motion: binary_sensor.basement_hall_motion
    media_player: media_player.lounge_echo_plus
  - name: Electric Cabinet
    icon: mdi:flash-outline
    light: light.basement_hall
  - name: Snug
    icon: mdi:filmstrip
    light: group.snug_lights
    motion: binary_sensor.snug_motion
    media_player: media_player.snug_echo_input
  - name: Dining Room
    icon: mdi:silverware-fork-knife
    light: light.dining_room
    motion: binary_sensor.dining_room_motion
    media_player: media_player.dining_room_echo_input
    climate: climate.basement
    humidity: climate.basement_thermostat_humidity
    temperature: sensor.basement_thermostat_temperature
    addons:
      - name: Printer
        icon: mdi:printer
        path: 'dwains-theme/addons/rooms/dining-room/printer/page.yaml'
        data:
          entity: sensor.brother_hl_3150cdw_series
  - name: Toliet
    icon: mdi:toilet
    light: light.toilet
    motion: binary_sensor.toilet_motion
  - name: Utility Room
    icon: mdi:washing-machine
    light: light.utility_room
    motion: binary_sensor.utility_room_motion
    media_player: media_player.utility_room_echo_dot
  - name: Brewery
    icon: mdi:beer-outline
    light: light.brewery