blueprint:
  name: Zone Entering Notification
  description: Send a notification to a device when a person enters a specific zone.
  domain: automation
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    zone_entity:
      name: Zone
      selector:
        entity:
          domain: zone
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications.
      selector:
        device:
          integration: mobile_app
  source_url: https://community.home-assistant.io/t/notify-entering-zone/255248
trigger:
  platform: state
  entity_id: !input 'person_entity'
variables:
  zone_entity: !input 'zone_entity'
  zone_state: '{{ states[zone_entity].name }}'
  person_entity: !input 'person_entity'
  person_name: '{{ states[person_entity].name }}'
condition:
  condition: template
  value_template: '{{ trigger.from_state.state != zone_state and trigger.to_state.state
    == zone_state }}'
action:
  domain: mobile_app
  type: notify
  device_id: !input 'notify_device'
  message: '{{ person_name }} has entered {{ zone_state }}'
