esphome:
  name: cat-feeder
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1196039b73e4bee9a68c5a96fb076438"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cat-Feeder Fallback Hotspot"
    password: "kSacMaQq095Q"

captive_portal:

text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Cat Feeder ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Cat Feeder IP
    ssid:
      name: Cat Feeder SSID
    bssid:
      name: Cat Feeder BSSID

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
    # timezone: Europe//London
    on_time:
      - hours: 7
        minutes: 05
        seconds: 45
        then:
          - if:
              condition:
                and:
                  - switch.is_off: morning_feed_complete
                  - switch.is_off: disable_next_feed
                  - switch.is_on: morning_feed_enabled
              then:
                - switch.turn_on: motor
                - homeassistant.service:
                    service: switch.turn_on
                    data:
                      entity_id: switch.morning_feed_complete
              else:
                - if:
                    condition:
                        - switch.is_on: disable_next_feed
                    then:
                      - homeassistant.service:
                          service: switch.turn_off
                          data:
                            entity_id: switch.disable_next_feed
          - homeassistant.service:
              service: switch.turn_on
              data:
                entity_id: switch.morning_feed_complete
          - homeassistant.service:
              service: switch.turn_off
              data:
                entity_id: switch.evening_feed_complete
      - hours: 17
        minutes: 35
        seconds: 45
        then:
          - if:
              condition:
                and:
                  - switch.is_off: evening_feed_complete
                  - switch.is_off: disable_next_feed
                  - switch.is_on: evening_feed_enabled
              then:
                - switch.turn_on: motor
                - homeassistant.service:
                    service: switch.turn_on
                    data:
                      entity_id: switch.evening_feed_complete
              else:
                - if:
                    condition:
                        - switch.is_on: disable_next_feed
                    then:
                      - homeassistant.service:
                          service: switch.turn_off
                          data:
                            entity_id: switch.disable_next_feed
          - homeassistant.service:
              service: switch.turn_on
              data:
                entity_id: switch.evening_feed_complete
          - homeassistant.service:
              service: switch.turn_off
              data:
                entity_id: switch.morning_feed_complete
    
# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Cat Feeder Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Cat Feeder WiFi Signal
    update_interval: 60s

switch:
  - platform: gpio
    pin: GPIO3
    name: "Dispenser Motor"
    id: motor
    on_turn_on:
      - script.execute: run_motor
  - platform: restart
    name: Cat Feeder Restart
    # Run conditions
  - platform: template
    id: morning_feed_enabled
    name: "Morning Feed Enabled"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
  - platform: template
    id: morning_feed_complete
    name: "Morning Feed Complete"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    id: evening_feed_enabled
    name: "Evening Feed Enabled"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
  - platform: template
    id: evening_feed_complete
    name: "Evening Feed Complete"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    id: disable_next_feed
    name: "Disable Next Feed"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

script:
  id: run_motor
  then:
    - delay: 10s
    - wait_until: 
        condition:
          binary_sensor.is_off: dispenser_rotating
        timeout: 60s
    - switch.turn_off: motor

binary_sensor:
  - platform: gpio
    name: "Dispenser Rotating"
    id: dispenser_rotating
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: False