substitutions:

###### CHANGE ME ######

  device_name: "nspanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

##### CHANGE ME #####



##### DO NOT CHANGE ANYTHING! #####

  nextion_update_url: "http://192.168.1.1:8123/local/nspanel_eu.tft"
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####