esphome:
  name: weather-station
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "fbc394d33335d950f1da0b97b9842b99"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather-Station Fallback Hotspot"
    password: "RlZ4VN3jyqoR"

captive_portal:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Weather Station ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Weather Station IP
    ssid:
      name: Weather Station SSID
    bssid:
      name: Weather Station BSSID

i2c:
  sda: 21
  scl: 22
  scan: True
  id: i2c_bus_a

# Switches
switch:
  - platform: restart
    name: Restart Weather Station

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Weather Station Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Weather Station WiFi Signal
    update_interval: 60s

  - platform: bme280_i2c
    temperature:
      name: "Weather Station Temperature"
      id: bme280_temperature
      oversampling: 16x
    pressure:
      name: "Weather Station Pressure"
      id: bme280_pressure
    humidity:
      name: "Weather Station Relative Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 60s
    
  - platform: bh1750
    name: "Weather Station Ambient Light"
    id: "bh1750_lux"
    address: 0x23
    update_interval: 60s

  # - platform: tsl2561
  #   name: "Weather Station Ambient Light"
  #   id: "tsl2561_lux"
  #   address: 0x39
  #   update_interval: 60s
  #   on_raw_value:
  #     then:
  #       lambda: |-
  #         // Automatically adjust the TSL2561 gain setting.
  #         // We need to track the gain independently as the gain_ property is private:
  #         static tsl2561::TSL2561Gain lastgain = tsl2561::TSL2561_GAIN_16X; // Make sure initial value matches yaml!
          
  #         if(isnan(x) && lastgain == tsl2561::TSL2561_GAIN_16X) { // Sensor is saturated, so lower the gain:
  #           // Note: id used here must match what is set in the yaml above.
  #           tsl2561_lux->set_gain(tsl2561::TSL2561_GAIN_1X);
  #           tsl2561_lux->setup();
  #           lastgain = tsl2561::TSL2561_GAIN_1X;
  #           ESP_LOGI("TSL2561 Auto-gain", "Lowered TSL2561 gain to 1x.");
  #           x = 15000;
  #           id(tsl2561_lux).state = x;
  #           id(tsl2561_lux).publish_state(x);
  #         }
  #         else if(x < 50.0 && lastgain == tsl2561::TSL2561_GAIN_1X){ // Low light, so raise the gain:
  #           // id used here must match what is set in the yaml above!
  #           tsl2561_lux->set_gain(tsl2561::TSL2561_GAIN_16X);
  #           tsl2561_lux->setup();
  #           lastgain = tsl2561::TSL2561_GAIN_16X;
  #           ESP_LOGI("TSL2561 Auto-gain", "Raised TSL2561 gain to 16x.");
  #         }

  - platform: template
    name: "Weather Station Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(bme280_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(bme280_pressure).state), 0.190234) - 1); // in meter
    update_interval: 60s

  - platform: template
    name: "Weather Station Humidity"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) /
        ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 60s